### ISSUE TITLE
eslint-restricted-globals vs confusing-browser-globals

### ISSUE THREAD

**Issue by edmorley** [doshisid/eslint-restricted-globals#2]
Hi!

I noticed that create-react-app now includes:
https://www.npmjs.com/package/confusing-browser-globals

...which seems to be identical to this package (and was authored by you in facebook/create-react-app#2286 :-))

It's just that [eslint-config-airbnb-base](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base) depends on this package and not the newly created `confusing-browser-globals` - so it seems like it might be worth trying to consolidate on one or the other?

**Comment by sidoshi** [comment]
Yes, you are right. This package solves same problem confusing-browser-globals in create react app. It's a good idea to change eslint-config-airbnb-base to depend on the CRA package.

**Comment by edmorley** [comment]
Great :-) I've opened airbnb/javascript/pull/1961.

**Comment by sidoshi** [comment]
Thank you for your work.

**Comment by ypresto** [comment]
To be sure, confusing-browser-globals is preferred over eslint-restricted-globals, right?
If it's right, it'd be better to deprecate npm package and archive this repo :)

**Comment by sidoshi** [comment]
@ypresto That's true. I will deprecate the package and archive this repo. Thanks for the suggestion.
