### ISSUE TITLE
License file in npm package & repo

### ISSUE THREAD

**Issue by dariagrudzien** [doshisid/eslint-restricted-globals#3]
@sidoshi Hi Siddharth, thank you for this package. Would you mind adding the MIT license file to the repo & the npm package? Without it we're not really able to use it, because it makes the npm package a distribution of proprietary code.

Many thanks.

**Comment by sidoshi** [comment]
Sorry, I was new to open source during the time I released this package and didn't know about license.

I will surely add one asap. Thanks for letting me know.

**Comment by dariagrudzien** [comment]
Thank so much!

**Comment by sidoshi** [comment]
I have merged #1 which adds MIT licence and cut a new release after that.

**Comment by sidoshi** [comment]
I have merged #1 which adds MIT licence and cut a new release.
